modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "Apache 2.0"

[[mods]]
modId = "title_screen_mobs"
version = "${version}"
displayName = "Title Screen Mobs"
authors = "IAFEnvoy"
description = '''
Add mobs to title screen
'''
logoFile = "logo.jpg"

[[dependencies.title_screen_mobs]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.title_screen_mobs]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "title_screen_mobs.mixins.json"
